# Generated by Django 2.1.5 on 2019-04-18 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190417_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elupicture',
            name='picture',
            field=models.ImageField(help_text='Rappel : Pour les élus uniquement.', upload_to='elus_pictures/'),
        ),
        migrations.AlterField(
            model_name='elupicture',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elu_picture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elurole',
            name='name',
            field=models.CharField(help_text='Rappel : Pour les élus uniquement. Rôles disponibles : maire, adjoint1, adjoint2, adjoint3', max_length=100),
        ),
    ]
