# Generated by Django 2.1.5 on 2019-04-18 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190418_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elurole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elu_role', to=settings.AUTH_USER_MODEL),
        ),
    ]
