# Generated by Django 2.1.2 on 2018-11-07 17:23

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cimetiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=250)),
                ('description', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField(help_text='test')),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SalleDeFete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=250)),
                ('description', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeHebergement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hebergement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vie_quotidienne.TypeHebergement'),
        ),
    ]
