# Generated by Django 2.1.5 on 2019-04-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vie_quotidienne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebergement',
            name='resume',
        ),
    ]
