# Generated by Django 2.1.5 on 2019-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_quotidienne', '0002_remove_hebergement_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebergement',
            name='resume',
            field=models.CharField(default='meh', max_length=280),
            preserve_default=False,
        ),
    ]
