# Generated by Django 2.1.2 on 2019-01-08 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vie_quotidienne', '0002_auto_20181107_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcheHoraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('debut', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='marche',
            name='fermeture',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='ouverture',
        ),
        migrations.AddField(
            model_name='commerce',
            name='adresse',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commerce',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hebergement',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
