# Generated by Django 2.1.2 on 2019-01-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vie_quotidienne', '0003_auto_20190108_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchehoraire',
            name='fin',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marchehoraire',
            name='marche',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vie_quotidienne.Marche'),
            preserve_default=False,
        ),
    ]
