# Generated by Django 2.1.5 on 2019-04-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_quotidienne', '0005_auto_20190124_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='resume',
            field=models.CharField(default=None, max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marchehoraire',
            name='jour',
            field=models.IntegerField(choices=[(0, 'Lundi')]),
        ),
    ]
