# Generated by Django 2.1.5 on 2019-04-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_quotidienne', '0006_auto_20190415_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='code_postal',
            field=models.CharField(default=35132, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marchehoraire',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10),
        ),
    ]
