# Generated by Django 2.1.5 on 2019-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_quotidienne', '0007_auto_20190416_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='header',
            field=models.ImageField(default=None, upload_to='commerces_header/'),
            preserve_default=False,
        ),
    ]
