# Generated by Django 2.1.5 on 2019-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_quotidienne', '0008_commerce_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='code_postal',
            field=models.CharField(default=35132, max_length=5),
            preserve_default=False,
        ),
    ]
