# Generated by Django 2.1.5 on 2019-07-03 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('cover', models.ImageField(null=True, upload_to='uploaded_images/association/')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='president', to=settings.AUTH_USER_MODEL)),
                ('secretaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretaire', to=settings.AUTH_USER_MODEL)),
                ('tresorier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tresorier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
