# Generated by Django 2.1.2 on 2019-01-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='nom',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
