# Generated by Django 2.1.2 on 2019-01-10 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_association_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='association_president', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='association',
            name='secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='association_secretaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='association',
            name='tresorier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='association_tresorier', to=settings.AUTH_USER_MODEL),
        ),
    ]
