# Generated by Django 2.1.5 on 2019-01-24 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_auto_20190110_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='president', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='association',
            name='secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='association',
            name='tresorier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tresorier', to=settings.AUTH_USER_MODEL),
        ),
    ]
