# Generated by Django 2.1.5 on 2019-03-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_auto_20190124_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploaded_images/association/'),
        ),
    ]
