# Generated by Django 2.1.2 on 2018-11-22 23:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distinction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('est_mairie', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('text', markdownx.models.MarkdownxField()),
                ('date', models.DateField(default=datetime.datetime(2018, 11, 22, 23, 3, 29, 930909, tzinfo=utc))),
                ('est_mairie', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrimoine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('adresse', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimoineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patrimoine_images/')),
                ('patrimoine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadre_de_vie.Patrimoine')),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=250)),
                ('prix', models.FloatField()),
                ('surface', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=250)),
                ('duree', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Travaux',
            },
        ),
    ]
