# Generated by Django 2.1.5 on 2019-04-18 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0005_association_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distinction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('est_mairie', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='association.Association', verbose_name='Propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Newpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('texte', markdownx.models.MarkdownxField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('est_mairie', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
            ],
        ),
        migrations.CreateModel(
            name='Patrimoine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('adresse', models.CharField(max_length=250)),
                ('patrimoine_image', models.ImageField(upload_to='patrimoine_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=250)),
                ('prix', models.FloatField()),
                ('surface', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=250)),
                ('duree', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Travaux',
            },
        ),
    ]
