# Generated by Django 2.1.5 on 2019-07-03 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distinction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('est_mairie', models.BooleanField(default=False)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='association.Association', verbose_name='Propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Newpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('texte', markdownx.models.MarkdownxField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('est_mairie', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
            ],
        ),
        migrations.CreateModel(
            name='Patrimoine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', markdownx.models.MarkdownxField()),
                ('adresse', models.CharField(max_length=250)),
                ('patrimoine_image', models.ImageField(upload_to='patrimoine_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=250)),
                ('prix', models.FloatField()),
                ('surface', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=250)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Travaux',
            },
        ),
        migrations.CreateModel(
            name='TypeTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Type travaux',
            },
        ),
        migrations.AddField(
            model_name='travail',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadre_de_vie.TypeTravail'),
        ),
    ]
