# Generated by Django 2.1.5 on 2019-04-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travail',
        ),
    ]
