# Generated by Django 2.1.2 on 2019-01-08 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0002_auto_20181123_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('text', markdownx.models.MarkdownxField()),
                ('date', models.DateField(default=datetime.datetime(2019, 1, 8, 10, 49, 48, 761725, tzinfo=utc))),
                ('est_mairie', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
