# Generated by Django 2.1.5 on 2019-04-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0002_delete_travail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=250)),
                ('duree', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Travaux',
            },
        ),
    ]
