# Generated by Django 2.1.2 on 2019-01-08 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0003_auto_20190108_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpaper',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 8, 16, 57, 32, 245919, tzinfo=utc)),
        ),
    ]
