# Generated by Django 2.1.5 on 2019-04-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0003_travail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travail',
            name='duree',
        ),
        migrations.AddField(
            model_name='travail',
            name='debut',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travail',
            name='fin',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
