# Generated by Django 2.1.5 on 2019-06-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0004_auto_20190418_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='distinction',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='travail',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadre_de_vie.TypeTravail'),
        ),
    ]
