# Generated by Django 2.1.5 on 2019-07-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0005_auto_20190627_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typetravail',
            options={'verbose_name_plural': 'Type travaux'},
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='date',
            new_name='debut',
        ),
        migrations.AddField(
            model_name='evenement',
            name='fin',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
