# Generated by Django 2.1.5 on 2019-07-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0006_auto_20190703_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='fin',
            field=models.DateTimeField(),
        ),
    ]
