# Generated by Django 2.1.5 on 2019-07-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0007_auto_20190703_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='fin',
            field=models.DateField(),
        ),
    ]
