# Generated by Django 2.1.2 on 2019-01-09 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0008_auto_20190109_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpaper',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
