# Generated by Django 2.1.2 on 2019-01-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_association_nom'),
        ('cadre_de_vie', '0009_auto_20190109_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpaper',
            old_name='text',
            new_name='texte',
        ),
        migrations.AddField(
            model_name='newpaper',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Association'),
        ),
    ]
