# Generated by Django 2.1.5 on 2019-01-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0010_auto_20190110_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimoineimage',
            name='patrimoine',
        ),
        migrations.AddField(
            model_name='patrimoine',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_de_vie.PatrimoineImage'),
            preserve_default=False,
        ),
    ]
