# Generated by Django 2.1.5 on 2019-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0011_auto_20190124_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimoine',
            name='image',
        ),
        migrations.AddField(
            model_name='patrimoine',
            name='patrimoine_image',
            field=models.ImageField(default=None, upload_to='patrimoine_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PatrimoineImage',
        ),
    ]
