# Generated by Django 2.1.5 on 2019-02-22 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_de_vie', '0012_auto_20190220_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpaper',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Association'),
        ),
    ]
