# Generated by Django 2.1.2 on 2018-11-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_municipale', '0002_auto_20181101_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='titre',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
