# Generated by Django 2.1.2 on 2018-11-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vie_municipale', '0003_bulletin_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='titre',
        ),
    ]
