# Generated by Django 2.1.2 on 2019-01-09 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vie_municipale', '0008_auto_20190108_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 9, 9, 21, 13, 543809, tzinfo=utc)),
        ),
    ]
