# Generated by Django 2.1.5 on 2019-04-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vie_municipale', '0013_auto_20190109_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='date',
        ),
    ]
