# Generated by Django 2.1.5 on 2019-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_municipale', '0014_remove_commission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseil',
            name='pdf',
            field=models.FileField(default=35132, upload_to='conseil_pdf/'),
            preserve_default=False,
        ),
    ]
